### ISSUE TITLE
Input fields connection with Google maps

### ISSUE THREAD

**Issue by svcody** [dicody/beep-beep#3]

**Comment by dicody** [comment]
Bing Maps API will be used, fits fine. REST API (e.g. http://dev.virtualearth.net/REST/v1/Routes?wayPoint.1=Riga%20Latvia&waypoint.2=Valmiera%20Latvia&optimize=timeWithTraffic&routeAttributes=routeSummariesOnly&key={register in Bing Maps and create a key}
